version: '3.3'
services:
  db:
    image: mysql:latest
    command: --max-allowed-packet=64M
    restart: always
    environment:
      MYSQL_DATABASE: 'npds'
      MYSQL_USER: 'app'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: 'dhaka'
    ports:
      - "3306:3306"
volumes: 
  mysql-data: